CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE device_status AS ENUM ('in_stock','reserved','sold','rma_under_repair','written_off');
CREATE TYPE payment_status AS ENUM ('pending','verified','rejected','refunded');
CREATE TYPE fulfillment_status AS ENUM ('new','confirmed','packing','packed','dispatched','delivered','cancelled','returned');
CREATE TABLE admin_users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(120) NOT NULL, email varchar(255) UNIQUE NOT NULL, role varchar(40) NOT NULL DEFAULT 'staff', password_hash text NOT NULL, is_active boolean NOT NULL DEFAULT true);
CREATE TABLE products (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(180) NOT NULL, brand varchar(80) NOT NULL, category varchar(80) NOT NULL, subcategory varchar(80) NOT NULL, description text, image_url text, image_urls jsonb DEFAULT '[]'::jsonb, base_cost numeric(14,2) NOT NULL CHECK(base_cost>=0), is_active boolean NOT NULL DEFAULT true);
CREATE TABLE product_variants (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), product_id uuid NOT NULL REFERENCES products(id), sku varchar(80) UNIQUE NOT NULL, color varchar(80), storage varchar(40), ram varchar(40), condition varchar(60) NOT NULL, price numeric(14,2) NOT NULL CHECK(price>=0), cost_price numeric(14,2) NOT NULL CHECK(cost_price>=0), warranty_months integer NOT NULL DEFAULT 12 CHECK(warranty_months>=0), stock_quantity integer NOT NULL DEFAULT 0 CHECK(stock_quantity>=0), low_stock_threshold integer NOT NULL DEFAULT 3 CHECK(low_stock_threshold>=0), listing_status varchar(20) NOT NULL DEFAULT 'available', is_active boolean NOT NULL DEFAULT true);
CREATE TABLE device_units (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), variant_id uuid NOT NULL REFERENCES product_variants(id), serial_number varchar(120) UNIQUE NOT NULL, imei_number varchar(20) UNIQUE, login_provider varchar(60), rebind_status varchar(40) DEFAULT 'pending', status device_status NOT NULL DEFAULT 'in_stock', received_at timestamptz NOT NULL DEFAULT now(), sold_at timestamptz);
CREATE TABLE customers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), customer_code varchar(40), name varchar(120) NOT NULL, phone varchar(40) UNIQUE NOT NULL, secondary_phone varchar(40), telegram_user_id varchar(80), telegram_username varchar(80), primary_address text, notes text, points integer NOT NULL DEFAULT 0, tier varchar(40) NOT NULL DEFAULT 'member', is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE shipping_destinations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), sr_no integer UNIQUE NOT NULL, state_code varchar(20) NOT NULL, state_name varchar(80) NOT NULL, from_city varchar(80) NOT NULL DEFAULT 'Yangon', to_city varchar(120) NOT NULL, zone varchar(20) NOT NULL, normal_price numeric(14,2) NOT NULL CHECK(normal_price>=0), courier_cost numeric(14,2) NOT NULL CHECK(courier_cost>=0), next_kg_rate numeric(14,2) NOT NULL CHECK(next_kg_rate>=0), is_active boolean NOT NULL DEFAULT true);
CREATE TABLE orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), customer_id uuid NOT NULL REFERENCES customers(id), order_code varchar(40) UNIQUE NOT NULL, order_source varchar(40) NOT NULL DEFAULT 'web', telegram_user_id varchar(80), customer_name varchar(120) NOT NULL, phone varchar(40) NOT NULL, destination_id uuid REFERENCES shipping_destinations(id), destination_city varchar(120), destination_state varchar(80), shipping_address text, street_address text, shipping_zone varchar(40), shipping_fee numeric(14,2) NOT NULL DEFAULT 0 CHECK(shipping_fee>=0), shipping_carrier varchar(80), payment_method varchar(40), total_amount numeric(14,2) NOT NULL CHECK(total_amount>=0), payment_status payment_status NOT NULL DEFAULT 'pending', fulfillment_status fulfillment_status NOT NULL DEFAULT 'new', payment_slip_url text, tracking_number varchar(100), delivered_at timestamptz, is_digital_only boolean NOT NULL DEFAULT false, packed_weight_kg numeric(8,2) NOT NULL DEFAULT 1.00, expected_courier_cost numeric(14,2) NOT NULL DEFAULT 0, actual_courier_cost numeric(14,2), required_deposit numeric(14,2) NOT NULL DEFAULT 10000, customer_paid_amount numeric(14,2) NOT NULL DEFAULT 0, customer_balance numeric(14,2) NOT NULL DEFAULT 0, cod_amount numeric(14,2) NOT NULL DEFAULT 0, customer_payment_status varchar(40) NOT NULL DEFAULT 'unpaid', courier_settlement_status varchar(40) NOT NULL DEFAULT 'not_applicable', commercial_frozen boolean NOT NULL DEFAULT false, delivery_fee_confirmed boolean NOT NULL DEFAULT false, internal_notes text, return_cost numeric(14,2) NOT NULL DEFAULT 0, return_reason text, failed_delivery_at timestamptz, customer_tier varchar(40) NOT NULL DEFAULT 'member', tier_discount_amount numeric(14,2) NOT NULL DEFAULT 0, tier_delivery_discount numeric(14,2) NOT NULL DEFAULT 0, points_earned integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE order_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL REFERENCES orders(id), product_id uuid NOT NULL REFERENCES products(id), variant_id uuid NOT NULL REFERENCES product_variants(id), device_unit_id uuid REFERENCES device_units(id), unit_price numeric(14,2) NOT NULL, cost_snapshot numeric(14,2) NOT NULL, quantity integer NOT NULL DEFAULT 1 CHECK(quantity>0));
CREATE TABLE bundles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(180) NOT NULL, description text, bundle_price numeric(14,2) NOT NULL, savings_amount numeric(14,2) NOT NULL, items_json jsonb NOT NULL, is_active boolean NOT NULL DEFAULT true);
CREATE TABLE order_bundle_sets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL REFERENCES orders(id), bundle_id uuid REFERENCES bundles(id), bundle_name varchar(180) NOT NULL, bundle_price numeric(14,2) NOT NULL, items_json jsonb NOT NULL);
CREATE TABLE tickets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ticket_code varchar(40) UNIQUE NOT NULL, order_code varchar(40) NOT NULL, order_item_id uuid REFERENCES order_items(id), serial_number varchar(120), customer_name varchar(120) NOT NULL, phone varchar(40) NOT NULL, category varchar(80) NOT NULL, priority varchar(30) NOT NULL DEFAULT 'normal', status varchar(40) NOT NULL DEFAULT 'claim_received', message_text text, warranty_start_at timestamptz, warranty_expires_at timestamptz, resolution varchar(40), resolution_cost numeric(14,2) NOT NULL DEFAULT 0 CHECK(resolution_cost>=0), refund_amount numeric(14,2) NOT NULL DEFAULT 0 CHECK(refund_amount>=0), replacement_variant_id uuid REFERENCES product_variants(id), resolved_at timestamptz);
CREATE TABLE staff_alerts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), type varchar(60) NOT NULL, title varchar(180) NOT NULL, body text NOT NULL, target_code varchar(80), is_read boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE receipt_settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), shop_name varchar(180) NOT NULL, address text, phone varchar(40), header_message text, footer_message text, paper_size integer NOT NULL DEFAULT 80 CHECK(paper_size IN(58,80)), show_barcode boolean NOT NULL DEFAULT true, show_qr boolean NOT NULL DEFAULT true);
CREATE TABLE system_audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), category varchar(40) NOT NULL DEFAULT 'system', event varchar(80) NOT NULL, actor varchar(120) NOT NULL DEFAULT 'system', target_code varchar(100), details text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE bot_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), telegram_user_id varchar(80) UNIQUE NOT NULL, language varchar(10) NOT NULL DEFAULT 'en', state_json jsonb NOT NULL DEFAULT '{}'::jsonb, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE suppliers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(180) NOT NULL, phone varchar(40), email varchar(255), address text, notes text, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE purchase_orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), po_code varchar(40) UNIQUE NOT NULL, supplier_id uuid NOT NULL REFERENCES suppliers(id), status varchar(30) NOT NULL DEFAULT 'ordered', total_cost numeric(14,2) NOT NULL CHECK(total_cost>=0), notes text, created_at timestamptz NOT NULL DEFAULT now(), received_at timestamptz);
CREATE TABLE purchase_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), purchase_order_id uuid NOT NULL REFERENCES purchase_orders(id), variant_id uuid NOT NULL REFERENCES product_variants(id), quantity integer NOT NULL CHECK(quantity>0), unit_cost numeric(14,2) NOT NULL CHECK(unit_cost>=0));
CREATE TABLE payment_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), bank_name varchar(120) NOT NULL, account_holder varchar(120) NOT NULL, account_number varchar(120) NOT NULL, instructions text, qr_code_url text, is_active boolean NOT NULL DEFAULT true, display_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE expenses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), expense_code varchar(40) UNIQUE NOT NULL, category varchar(80) NOT NULL, description text NOT NULL, amount numeric(14,2) NOT NULL CHECK(amount>=0), payment_method varchar(40) NOT NULL, expense_date timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE order_payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL REFERENCES orders(id) ON DELETE CASCADE, payment_type varchar(40) NOT NULL, amount numeric(14,2) NOT NULL, payment_method varchar(40) NOT NULL DEFAULT 'kbzpay', status varchar(40) NOT NULL DEFAULT 'pending', reference varchar(120), slip_url text, recorded_by varchar(120) NOT NULL DEFAULT 'customer', verified_by varchar(120), verified_at timestamptz, reversal_of_id uuid, notes text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE courier_settlement_batches (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), batch_code varchar(60) UNIQUE NOT NULL, courier_name varchar(80) NOT NULL DEFAULT 'Royal Express', bank_account varchar(120) NOT NULL, transfer_reference varchar(120) NOT NULL, settlement_date timestamptz NOT NULL, total_collected numeric(14,2) NOT NULL DEFAULT 0, total_courier_fees numeric(14,2) NOT NULL DEFAULT 0, other_fees numeric(14,2) NOT NULL DEFAULT 0, bank_received_amount numeric(14,2) NOT NULL CHECK(bank_received_amount>=0), status varchar(40) NOT NULL DEFAULT 'completed', discrepancy_amount numeric(14,2) NOT NULL DEFAULT 0, recorded_by varchar(120) NOT NULL, notes text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE courier_settlement_allocations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), settlement_batch_id uuid NOT NULL REFERENCES courier_settlement_batches(id) ON DELETE CASCADE, order_id uuid NOT NULL REFERENCES orders(id) ON DELETE CASCADE, expected_cod numeric(14,2) NOT NULL, allocated_collected numeric(14,2) NOT NULL, expected_courier_fee numeric(14,2) NOT NULL, allocated_courier_fee numeric(14,2) NOT NULL, net_order_payout numeric(14,2) NOT NULL, allocated_by varchar(120) NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE media_uploads (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), filename varchar(255) NOT NULL, mime_type varchar(100) NOT NULL DEFAULT 'image/webp', size_bytes integer NOT NULL, data text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX media_uploads_created_at_idx ON media_uploads(created_at DESC);
CREATE INDEX device_units_variant_status_idx ON device_units(variant_id,status);
CREATE INDEX product_variants_product_id_idx ON product_variants(product_id);
CREATE INDEX device_units_variant_id_idx ON device_units(variant_id);
CREATE INDEX device_units_status_idx ON device_units(status);
CREATE INDEX device_units_serial_number_idx ON device_units(serial_number);
CREATE INDEX orders_created_at_idx ON orders(created_at DESC);
CREATE INDEX orders_status_idx ON orders(payment_status,fulfillment_status);
CREATE INDEX orders_phone_idx ON orders(phone);
CREATE INDEX orders_customer_id_idx ON orders(customer_id);
CREATE INDEX customers_telegram_user_idx ON customers(telegram_user_id);
CREATE INDEX customers_active_idx ON customers(is_active);
CREATE INDEX customers_tier_idx ON customers(tier);
CREATE INDEX order_items_order_id_idx ON order_items(order_id);
CREATE INDEX order_items_variant_id_idx ON order_items(variant_id);
CREATE INDEX order_bundle_sets_order_idx ON order_bundle_sets(order_id);
CREATE INDEX order_bundle_sets_bundle_idx ON order_bundle_sets(bundle_id);
CREATE INDEX tickets_serial_idx ON tickets(serial_number);
CREATE INDEX tickets_order_code_idx ON tickets(order_code);
CREATE INDEX tickets_status_idx ON tickets(status);
CREATE INDEX tickets_order_item_idx ON tickets(order_item_id);
CREATE INDEX system_audit_logs_created_idx ON system_audit_logs(created_at DESC);
CREATE INDEX audit_logs_event_idx ON system_audit_logs(event);
CREATE INDEX audit_logs_category_created_idx ON system_audit_logs(category,created_at DESC);
CREATE INDEX suppliers_active_idx ON suppliers(is_active);
CREATE INDEX purchase_orders_supplier_idx ON purchase_orders(supplier_id);
CREATE INDEX purchase_orders_status_idx ON purchase_orders(status);
CREATE INDEX purchase_items_order_idx ON purchase_items(purchase_order_id);
CREATE INDEX purchase_items_variant_idx ON purchase_items(variant_id);
CREATE INDEX expenses_date_idx ON expenses(expense_date DESC);
CREATE INDEX expenses_category_idx ON expenses(category);
CREATE INDEX payment_accounts_active_idx ON payment_accounts(is_active);
CREATE INDEX payment_accounts_order_idx ON payment_accounts(display_order);
CREATE INDEX shipping_destinations_city_idx ON shipping_destinations(to_city);
CREATE INDEX shipping_destinations_state_idx ON shipping_destinations(state_code);
CREATE INDEX orders_customer_payment_status_idx ON orders(customer_payment_status);
CREATE INDEX orders_courier_settlement_status_idx ON orders(courier_settlement_status);
CREATE INDEX order_payments_order_id_idx ON order_payments(order_id);
CREATE INDEX order_payments_status_idx ON order_payments(status);
CREATE INDEX order_payments_type_idx ON order_payments(payment_type);
CREATE INDEX courier_settlements_date_idx ON courier_settlement_batches(settlement_date);
CREATE INDEX courier_settlements_status_idx ON courier_settlement_batches(status);
CREATE INDEX courier_allocations_batch_idx ON courier_settlement_allocations(settlement_batch_id);
CREATE INDEX courier_allocations_order_idx ON courier_settlement_allocations(order_id);
CREATE INDEX customers_customer_code_idx ON customers(customer_code);
CREATE INDEX customers_telegram_username_idx ON customers(telegram_username);
CREATE INDEX customers_secondary_phone_idx ON customers(secondary_phone);
CREATE TABLE IF NOT EXISTS bot_message_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), key varchar(80) NOT NULL UNIQUE, label varchar(160) NOT NULL, description text, trigger_source varchar(80) NOT NULL DEFAULT 'manual', content text NOT NULL, placeholders jsonb DEFAULT '[]'::jsonb, updated_at timestamptz NOT NULL DEFAULT now(), updated_by varchar(120));
CREATE INDEX IF NOT EXISTS bot_message_templates_key_idx ON bot_message_templates(key);
CREATE TABLE IF NOT EXISTS ai_sales_qa (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), question text NOT NULL, answer text NOT NULL, category varchar(80) NOT NULL DEFAULT 'general', is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), updated_by varchar(120));
CREATE INDEX IF NOT EXISTS ai_sales_qa_created_idx ON ai_sales_qa(created_at);
CREATE INDEX IF NOT EXISTS ai_sales_qa_category_idx ON ai_sales_qa(category);

