import type { Order, Product } from "./types";

export const products: Product[] = [
  {
    id: "razer-blackshark-v2x",
    name: "BlackShark V2 X",
    brand: "Razer",
    category: "Gaming Gadgets",
    subcategory: "Gaming Headphones",
    image:
      "https://images.unsplash.com/photo-1599669454699-248893623440?auto=format&fit=crop&w=900&q=85",
    tagline: "Lightweight esports headset with clear positional audio.",
    specs: [
      { label: "Driver", value: "50mm" },
      { label: "Mic", value: "Cardioid" },
      { label: "Weight", value: "240g" },
    ],
    price: 189000,
    cost: 142000,
    stock: 8,
    sku: "RZR-BSV2X-BLK",
    color: "Black",
    condition: "Brand New Sealed",
    warranty: 6,
  },
  {
    id: "memo-dl05-cooler",
    name: "DL05 Phone Cooler",
    brand: "MEMO",
    category: "Gaming Gadgets",
    subcategory: "Cooling Fans",
    image:
      "https://images.unsplash.com/photo-1601524909162-ae8725290836?auto=format&fit=crop&w=900&q=85",
    tagline: "Magnetic RGB cooling for long mobile gaming sessions.",
    specs: [
      { label: "Cooling", value: "Semiconductor" },
      { label: "Power", value: "10W" },
      { label: "Mount", value: "Magnetic" },
    ],
    price: 65000,
    cost: 42000,
    stock: 18,
    sku: "MEMO-DL05-RGB",
    color: "Black",
    condition: "Brand New Sealed",
    warranty: 3,
  },
  {
    id: "gamesir-g8",
    name: "G8 Galileo Controller",
    brand: "GameSir",
    category: "Gaming Gadgets",
    subcategory: "Controllers",
    image:
      "https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=900&q=85",
    tagline: "Console-style mobile control with Hall Effect sticks.",
    specs: [
      { label: "Sticks", value: "Hall Effect" },
      { label: "Port", value: "USB-C" },
      { label: "Platform", value: "Android/iOS" },
    ],
    price: 225000,
    cost: 174000,
    stock: 7,
    sku: "GMS-G8-GALILEO",
    color: "Silver",
    condition: "Brand New Sealed",
    warranty: 6,
  },
  {
    id: "anker-prime",
    name: "Prime 100W GaN Charger",
    brand: "Anker",
    category: "Gaming Gadgets",
    subcategory: "Charging Gear",
    image:
      "https://images.unsplash.com/photo-1587033411391-5d9e51cce126?auto=format&fit=crop&w=900&q=85",
    tagline: "Fast, stable power for phones, tablets, and gaming laptops.",
    specs: [
      { label: "Output", value: "100W Max" },
      { label: "Ports", value: "2C + 1A" },
      { label: "Tech", value: "GaNPrime" },
    ],
    price: 329000,
    cost: 218000,
    stock: 14,
    sku: "ANK-PRIME-100W",
    color: "Black",
    condition: "Brand New Sealed",
    warranty: 18,
  },
  {
    id: "moondrop-chu2-dsp",
    name: "CHU II DSP Gaming Earbuds",
    brand: "Moondrop",
    category: "Gaming Gadgets",
    subcategory: "Gaming Earbuds",
    image:
      "https://images.unsplash.com/photo-1608156639585-b3a032ef9689?auto=format&fit=crop&w=900&q=85",
    tagline: "Low-latency USB-C audio with detailed footsteps and voice chat.",
    specs: [
      { label: "Connector", value: "USB-C" },
      { label: "Driver", value: "10mm" },
      { label: "Mic", value: "Inline" },
    ],
    price: 98000,
    cost: 71000,
    stock: 11,
    sku: "MD-CHU2-DSP",
    color: "Silver",
    condition: "Brand New Sealed",
    warranty: 6,
  },
  {
    id: "pubg-starter",
    name: "PUBG Mobile Starter Account",
    brand: "PUBG Mobile",
    category: "PUBG Accounts",
    subcategory: "Starter Accounts",
    image:
      "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=900&q=85",
    tagline: "A clean, verified account ready for your first rank push.",
    specs: [
      { label: "Level", value: "Lv. 45+" },
      { label: "Outfits", value: "20+" },
      { label: "Security", value: "Rebind ready" },
    ],
    price: 95000,
    cost: 70000,
    stock: 12,
    sku: "PUBG-STARTER-45",
    color: "Global",
    condition: "Verified Digital Account",
    warranty: 1,
  },
  {
    id: "pubg-competitive",
    name: "PUBG Competitive Account",
    brand: "PUBG Mobile",
    category: "PUBG Accounts",
    subcategory: "Competitive Accounts",
    image:
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=85",
    tagline: "Competitive inventory with upgraded weapon finishes.",
    specs: [
      { label: "Level", value: "Lv. 70+" },
      { label: "Gun Labs", value: "3+" },
      { label: "Mythics", value: "8+" },
    ],
    price: 650000,
    cost: 490000,
    stock: 4,
    sku: "PUBG-COMP-70",
    color: "Global",
    condition: "Verified Digital Account",
    warranty: 1,
  },
  {
    id: "pubg-collector",
    name: "PUBG Collector Account",
    brand: "PUBG Mobile",
    category: "PUBG Accounts",
    subcategory: "Collector Accounts",
    image:
      "https://images.unsplash.com/photo-1598550476439-6847785fcea6?auto=format&fit=crop&w=900&q=85",
    tagline: "Rare cosmetics and premium collections, ownership verified.",
    specs: [
      { label: "Level", value: "Lv. 80+" },
      { label: "Gun Labs", value: "10+" },
      { label: "Mythics", value: "25+" },
    ],
    price: 2450000,
    cost: 1920000,
    stock: 2,
    sku: "PUBG-COLLECT-80",
    color: "Global",
    condition: "Verified Digital Account",
    warranty: 1,
  },
];

export const orders: Order[] = [
  {
    id: "MHOP-260828-1042",
    customer: "Thiri Aung",
    channel: "Telegram",
    amount: 290000,
    payment: "Pending",
    fulfillment: "New",
    item: "GameSir G8 + MEMO DL05",
    created: "10:42 AM",
  },
  {
    id: "MHOP-260828-1038",
    customer: "Min Khant",
    channel: "Web",
    amount: 650000,
    payment: "Verified",
    fulfillment: "Packing",
    item: "PUBG Competitive Account",
    created: "10:18 AM",
  },
  {
    id: "MHOP-260828-1021",
    customer: "Moe Myint",
    channel: "POS",
    amount: 189000,
    payment: "Verified",
    fulfillment: "Delivered",
    item: "Razer BlackShark V2 X",
    created: "9:31 AM",
  },
  {
    id: "MHOP-260827-0988",
    customer: "Nandar Hlaing",
    channel: "Web",
    amount: 98000,
    payment: "Verified",
    fulfillment: "Dispatched",
    item: "Moondrop CHU II DSP",
    created: "Yesterday",
  },
];

export const formatMMK = (value: number) =>
  `${new Intl.NumberFormat("en-US").format(value)} MMK`;
