import { getAlertsAction } from "@/app/actions/admin";
import { AlertCenter } from "@/components/alert-center";
import { PageHeading } from "@/components/page-heading";
export const dynamic = "force-dynamic";
export default async function AlertsPage() {
  const alerts = await getAlertsAction();
  return (
    <>
      <PageHeading
        eyebrow="Operations inbox"
        title="Staff alerts"
        description="Review payment, order, shipment, and stock events generated by the business workflow."
      />
      <AlertCenter alerts={alerts} />
    </>
  );
}
